import Link from "next/link";
import { Arrow, Sparkle } from "@/components/icons";
import { LearningStage } from "@/components/learning-stage";
import { SiteHeader } from "@/components/site-header";

const principles = [["Think aloud", "Turn vague instincts into clear, testable reasoning."], ["Learn in steps", "Build confidence through questions, not answer dumps."], ["Own the solution", "Write code only after the idea is truly yours."]];

export default function Home() {
  return <main><SiteHeader />
    <section className="relative mx-auto max-w-7xl overflow-hidden px-5 pb-20 pt-14 sm:px-8 sm:pb-28 sm:pt-24"><div className="absolute right-0 top-0 -z-10 h-96 w-96 rounded-full bg-[#EEE9FF] blur-3xl" />
      <div className="max-w-3xl"><p className="mb-6 inline-flex items-center gap-2 rounded-full bg-lilac px-4 py-2 text-sm font-bold text-[#5B46C3]"><Sparkle /> A calmer way to learn programming</p><h1 className="text-5xl font-black leading-[1.03] tracking-tight sm:text-7xl">Think it through.<br /><span className="text-[#6957D9]">Then code it.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">CodeCompile is your guided problem-solving space. It helps you build computational thinking instead of handing you the answer.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/session" className="inline-flex items-center gap-3 rounded-full bg-ink px-6 py-3.5 font-bold text-white transition hover:bg-slate-700">Try the guided session <Arrow /></Link><a href="#how-it-works" className="rounded-full border border-slate-300 bg-white px-6 py-3.5 font-bold text-slate-700">See how it works</a></div></div>
      <div className="mt-16 max-w-5xl rounded-[2rem] border border-white bg-white/85 p-5 shadow-soft backdrop-blur sm:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold">A guided path, not a chat thread</p><p className="mt-1 text-sm text-slate-500">Every good solution starts with a good question.</p></div><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-[#177044]">Your pace</span></div><LearningStage /></div>
    </section>
    <section id="how-it-works" className="bg-ink px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#BDB0FF]">How it works</p><h2 className="mt-4 max-w-2xl text-4xl font-bold tracking-tight">You bring the problem. We help you uncover the path.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[["01", "Describe it", "Put the problem into your own words."], ["02", "Explore it", "Question assumptions, edge cases, and trade-offs."], ["03", "Build it", "Move to implementation when the reasoning is solid."]].map(([number, title, body]) => <article key={number} className="rounded-3xl bg-white/10 p-6"><p className="text-sm font-bold text-[#BDB0FF]">{number}</p><h3 className="mt-10 text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-300">{body}</p></article>)}</div></div></section>
    <section id="principles" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#6957D9]">Built for deeper learning</p><div className="mt-8 grid gap-5 md:grid-cols-3">{principles.map(([title, body]) => <article key={title} className="rounded-3xl border border-slate-200 bg-white p-7"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-peach font-bold text-[#A3532B]">✦</div><h3 className="mt-7 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{body}</p></article>)}</div></section>
  </main>;
}
